//Redistribution and use in source and binary forms, with or without
//modification, are permitted provided that the following conditions are met:
//
//1. Redistributions of source code must retain the above copyright notice, this
//   list of conditions and the following disclaimer. 
//2. Redistributions in binary form must reproduce the above copyright notice,
//   this list of conditions and the following disclaimer in the documentation
//   and/or other materials provided with the distribution.
//
//THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
//ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
//WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
//DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
//ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
//(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
//The views and conclusions contained in the software and documentation are those
//of the authors and should not be interpreted as representing official policies, 
//either expressed or implied, of the FreeBSD Project.
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.02 at 09:28:30 AM PDT 
//
package de.learnlib.ralib.automata.xml;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the automata.xml package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of
     * schema derived classes for package: automata.xml
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RegisterAutomaton }
     *
     */
    public RegisterAutomaton createRegisterAutomaton() {
        return new RegisterAutomaton();
    }

    /**
     * Create an instance of {@link RegisterAutomaton.Transitions }
     *
     */
    public RegisterAutomaton.Transitions createRegisterAutomatonTransitions() {
        return new RegisterAutomaton.Transitions();
    }

    /**
     * Create an instance of {@link RegisterAutomaton.Transitions.Transition }
     *
     */
    public RegisterAutomaton.Transitions.Transition createRegisterAutomatonTransitionsTransition() {
        return new RegisterAutomaton.Transitions.Transition();
    }

    /**
     * Create an instance of {@link RegisterAutomaton.Transitions.Transition.Assignments
     * }
     *
     */
    public RegisterAutomaton.Transitions.Transition.Assignments createRegisterAutomatonTransitionsTransitionAssignments() {
        return new RegisterAutomaton.Transitions.Transition.Assignments();
    }

    /**
     * Create an instance of {@link RegisterAutomaton.Locations }
     *
     */
    public RegisterAutomaton.Locations createRegisterAutomatonLocations() {
        return new RegisterAutomaton.Locations();
    }

    /**
     * Create an instance of {@link RegisterAutomaton.Globals }
     *
     */
    public RegisterAutomaton.Globals createRegisterAutomatonGlobals() {
        return new RegisterAutomaton.Globals();
    }

    /**
     * Create an instance of {@link RegisterAutomaton.Constants }
     *
     */
    public RegisterAutomaton.Constants createRegisterAutomatonConstants() {
        return new RegisterAutomaton.Constants();
    }

    /**
     * Create an instance of {@link RegisterAutomaton.Alphabet }
     *
     */
    public RegisterAutomaton.Alphabet createRegisterAutomatonAlphabet() {
        return new RegisterAutomaton.Alphabet();
    }

    /**
     * Create an instance of {@link RegisterAutomaton.Alphabet.Outputs }
     *
     */
    public RegisterAutomaton.Alphabet.Outputs createRegisterAutomatonAlphabetOutputs() {
        return new RegisterAutomaton.Alphabet.Outputs();
    }

    /**
     * Create an instance of {@link RegisterAutomaton.Alphabet.Outputs.Symbol }
     *
     */
    public RegisterAutomaton.Alphabet.Outputs.Symbol createRegisterAutomatonAlphabetOutputsSymbol() {
        return new RegisterAutomaton.Alphabet.Outputs.Symbol();
    }

    /**
     * Create an instance of {@link RegisterAutomaton.Alphabet.Inputs }
     *
     */
    public RegisterAutomaton.Alphabet.Inputs createRegisterAutomatonAlphabetInputs() {
        return new RegisterAutomaton.Alphabet.Inputs();
    }

    /**
     * Create an instance of {@link RegisterAutomaton.Alphabet.Inputs.Symbol }
     *
     */
    public RegisterAutomaton.Alphabet.Inputs.Symbol createRegisterAutomatonAlphabetInputsSymbol() {
        return new RegisterAutomaton.Alphabet.Inputs.Symbol();
    }

    /**
     * Create an instance of {@link RegisterAutomaton.Transitions.Transition.Assignments.Assign
     * }
     *
     */
    public RegisterAutomaton.Transitions.Transition.Assignments.Assign createRegisterAutomatonTransitionsTransitionAssignmentsAssign() {
        return new RegisterAutomaton.Transitions.Transition.Assignments.Assign();
    }

    /**
     * Create an instance of {@link RegisterAutomaton.Locations.Location }
     *
     */
    public RegisterAutomaton.Locations.Location createRegisterAutomatonLocationsLocation() {
        return new RegisterAutomaton.Locations.Location();
    }

    /**
     * Create an instance of {@link RegisterAutomaton.Globals.Variable }
     *
     */
    public RegisterAutomaton.Globals.Variable createRegisterAutomatonGlobalsVariable() {
        return new RegisterAutomaton.Globals.Variable();
    }

    /**
     * Create an instance of {@link RegisterAutomaton.Constants.Constant }
     *
     */
    public RegisterAutomaton.Constants.Constant createRegisterAutomatonConstantsConstant() {
        return new RegisterAutomaton.Constants.Constant();
    }

    /**
     * Create an instance of {@link RegisterAutomaton.Alphabet.Outputs.Symbol.Param
     * }
     *
     */
    public RegisterAutomaton.Alphabet.Outputs.Symbol.Param createRegisterAutomatonAlphabetOutputsSymbolParam() {
        return new RegisterAutomaton.Alphabet.Outputs.Symbol.Param();
    }

    /**
     * Create an instance of {@link RegisterAutomaton.Alphabet.Inputs.Symbol.Param
     * }
     *
     */
    public RegisterAutomaton.Alphabet.Inputs.Symbol.Param createRegisterAutomatonAlphabetInputsSymbolParam() {
        return new RegisterAutomaton.Alphabet.Inputs.Symbol.Param();
    }

}
